### ISSUE TITLE
Update Groovy version to 1.7.5

### ISSUE THREAD

**Issue by ghost** [krasserm/ipf#12]
- Resolve maven plug-in dependencies
- Resolve all compile problems
- Resolve all test problems
- Update basic archetype
- Update wiki
- Do smoke tests, within Eclipse, in modules CDA, HL7 and HL7DSL

**Comment by krasserm** [comment]
Thanks Mitko for starting with this. Highly appreciated!

**Comment by ghost** [comment]
Groovy updated to version 1.7.5. Closed by 7d073f8a1ae9a79ae1a4939f5e24e175ad4cf7df
