### ISSUE TITLE
Missing Quartz transitive dependency

### ISSUE THREAD

**Issue by ohr** [krasserm/ipf#2]
Until version 1.6.6, Quartz has a dependency to commons-collections 3.2, but fails to note this in its pom. If commons-collections 3.2 is not accidentally loaded by other modules, scheduling a Flow Purge triggers an error.
In commons-flow, depend on a recent quartz version (e.g. 1.8.3; note: groupId became org.quartz-scheduler) or explicitly depend on commons-collections 3.2.

**Comment by krasserm** [comment]
Thanks for reporting. I'll take care of it latest when I'm back from vacation (next week).

**Comment by krasserm** [comment]
Fixed with http://github.com/krasserm/ipf/commit/4cc6facedac5d925571b85d52e6552c78559091e
