### ISSUE TITLE
Flow Purger tries to delete all obsolete flows in Derby

### ISSUE THREAD

**Issue by ohr** [krasserm/ipf#22]
Even though the code indicates that only 100 flows are deleted in a loop, I got an memory-related exception (Derby 10.4.1.2):

org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not execute query; uncategorized SQLException for SQL [select this_.C_
4968 ID as C1_0_0_, this_.C_ACK_COUNT_EXPECTED as C2_0_0_, this_.C_APPLICATION as C3_0_0_, this_.C_CREATION_TIME as C4_0_0_, this_.C_DERIVED_STATUS as C5_
4968 0_0_, this_.FLOW_MESSAGE_ID as FLOW9_0_0_, this_.C_PACKET as C6_0_0_, this_.C_REPLAY_COUNT as C7_0_0_, this_.C_REPLAY_TIME as C8_0_0_ from PLATFORM.T
4968 _FLOW this_ where this_.C_CREATION_TIME<? and this_.C_APPLICATION=? order by this_.C_CREATION_TIME asc]; SQL state [XJ001]; error code [0]; Java exce
4968 ption: 'GC overhead limit exceeded: java.lang.OutOfMemoryError'.; nested exception is java.sql.SQLException: Java exception: 'GC overhead limit excee
4968 ded: java.lang.OutOfMemoryError'.
4969 at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
4970 at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
4971 at ....
org.openehealth.ipf.commons.flow.FlowManagerBase.purgeFlows(FlowManagerBase.java:100)
.....
4988 at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
4989 at $Proxy54.purgeFlows(Unknown Source)

In http://tim.oreilly.com/pub/a/onjava/2007/01/31/tuning-derby.html?page=1, it is stated that Derby does NOT provide something to restrict the result set like Oracle (where rownum< xxx) or MySQL (LIMIT xxx), so the restriction in Hibernate is useless and you have to work with scrollable result sets. The pattern described in the Hibernate docs is:

Session session = sessionFactory.openSession();
Transaction tx = session.beginTransaction();
Criteria query = session.createCriteria(myCriteria).setCacheMode(IGNORE).setFetchSize(200);
ScrollableResults results = query.scroll(ScrollMode.FORWARD_ONLY);
int count=0;
while ( results.next() ) {
    Type result = (Type) results.get(0);
    result.updateStuff(...);
    if ( ++count % 100 == 0 ) {
        //flush a batch of updates and release memory:
        session.flush();
        session.clear();
    }
}

**Comment by ghost** [comment]
Updated Hibernate and Derby versions. Closed by 35522c15e27a1ad865f1418e834e061489822527
