### ISSUE TITLE
SSL-related unit tests fail in platform-camel/ihe/pixpdq

### ISSUE THREAD

**Issue by unixoid** [krasserm/ipf#3]
platform-camel/ihe/pixpdq/src/test/groovy/org/openehealth/ipf/platform/camel/ihe/pixpdq/iti21/TestIti21.groovy#testSSLFailure*() methods run under Windows, but fail under Linux (in Hudson).  Temporarily @Ignore'd.

**Comment by krasserm** [comment]
Preliminary fix committed
