### ISSUE TITLE
ITI-47 raw wsdl definition has wrong soap actions

### ISSUE THREAD

**Issue by 4effo** [krasserm/ipf#37]
SOAP Action and WS-Addressing action should be equal. This is not the case in the ITI-47 wsdl definition.

This issue is critical for using iti-47 with CXF 2.3.2 (comes with Camel 2.6.0).
Affected are all 2.2 milestones up to m5.

**Comment by unixoid** [comment]
closed by https://github.com/krasserm/ipf/commit/eec1df23f319b7ce6912df443672658139723606
