### ISSUE TITLE
Support for using FlowManagement functionality from Java routes

### ISSUE THREAD

**Issue by sathisht** [krasserm/ipf#39]
Currently the FlowManager can be used only from Groovy routes. It would be great if we can use it from Java routes as well. Currently a lot of initialization happens in Flow_ProcessorDefinition classes for the correct working for flow management functionality. Just using Flow_Processor classes in Java routes doesn't seem to work.

**Comment by krasserm** [comment]
Won't fix as explained in http://groups.google.com/group/ipf-user/browse_thread/thread/76c14326d72e35bb. Should another solution be found we can still re-open this ticket.
