### ISSUE TITLE
Try DSLD for the IPF Groovy DSL extensions

### ISSUE THREAD

**Issue by ghost** [krasserm/ipf#62]
We could enrich our artifacts with DSL extension metadata to have type inference for the Groovy DSL extensions in Eclipse.

Check the following links for more info:
http://blog.springsource.com/2011/05/08/better-dsl-support-in-groovy-eclipse/
http://docs.codehaus.org/display/GROOVY/DSL+Descriptors+for+Groovy-Eclipse#DSLDescriptorsforGroovy-Eclipse-Pointcuts

**Comment by krasserm** [comment]
We should extend the https://github.com/krasserm/ipf-labs/tree/master/maven/maven-dsldoc-plugin (which already generates the DSL descriptors for IDEA) to generate the descriptors for Eclipse. WDYT?

**Comment by ghost** [comment]
Yes, our dsldoc maven plugin should be extended to generate DSLDs for Eclipse additionally.

**Comment by ghost** [comment]
I added generation of Eclipse DSL descriptors in the dsldoc-maven-plugin version 1.3 and updated the docs. 
@Martin Hope it gives you reason to come back to the IPF Eclipse user group ...  :)

**Comment by krasserm** [comment]
Am 01.06.2011 17:15 schrieb "mkolev" <
reply@reply.github.com>:

> I added generation of Eclipse DSL descriptors in the dsldoc-maven-plugin
> version 1.3 and updated the docs.

Great work, Mitko. Really like it.

> @Martin Hope it gives you reason to have you back in the IPF Eclipse user
> group ...  :)

Let's say, I have the choice again :)
