### ISSUE TITLE
Research auto-completion of the HL7 DSL in Eclipse DSLD

### ISSUE THREAD

**Issue by ghost** [krasserm/ipf#68]
Is Eclipse DSLD powerful enough so that we could define DSLD descriptors for the HL7v2 DSL?
Currently, if someone has to use the HL7 DSL  he has to know the message structure.

**Comment by krasserm** [comment]
Generating DSLDs for HL7v2 does require access to the HL7v2 schema definitions (in whatever format). AFAIK, HL7.org didn't publish these schema definitions. It's only the HAPI project that has exclusive access to it. Ask Christian Ohr for more details on that.

Should we however get access to the complete schema definitions then it would IMHO make more sense to replace the dynamic dispatch, that is currently done in the *Adapter classes, with a static dispatch in that all the DSL elements are methods on classes that are generated from the schema definitions. In this case you could use the default code-completion feature of any IDE and we could also generate a HL7v2 DSL for Scala and other languages as well.

Thoughts?

**Comment by ghost** [comment]
Hi Martin,

I did not intend to use schemas in whatever form to infer the types for the IPF HL7 DSL (it is also possible to create a static DSLD script).
Instead I wanted to evaluate the adapted HAPI structure and let the Eclipse Groovy plugin use this info. I am not really sure  if the plugin can handle such dynamic, but generally we could make a suggestion to extend the plugin functionality if something is not possible. In other words, I will give it a try and see what could be done.

What you suggested is a different approach to achieve the desired type inference (or the auto completion). I am not sure if I get you right, but is not an implementation of such static dispatch already offered by the HAPI library?

Regards,
Mitko

**Comment by ghost** [comment]
@Martin 
I made progress on this: http://i000174.blogspot.com/2011/06/hl7-2x-dsl-with-auto-completion.html
I would appreciate your feedback. We could make a separate announcement in the mailing lists when we release and update the docs.

**Comment by krasserm** [comment]
@mitko I'm currently in London talking at Scala eXchange - will review it when I'm back. Thanks in advance for summarising your work in a blog post. Will read it soon and give you feedback.

**Comment by krasserm** [comment]
Just read the blog post - good work! I only wonder if the introduction of type parameters in MessageAdapter etc breaks existing code? I've seen that no unit tests were modified, so I guess not ... just want to hear your confirmation.

**Comment by ghost** [comment]
Hi Martin.

The type parameters do not, and should not, break any existing code. As you
saw  the tests work as they did without any modifications. We have a number
of internal projects that we have tested with - no issues were found there
as well.

Next step for IPF would be to add some unit tests that show the usage, and
of course update the IPF docs to shows the benefits.

Regards,
Mitko

**Comment by unixoid** [comment]
Can this issue be closed?

**Comment by ghost** [comment]
- Documentation updated. 
- Documentation examples up to section 'Iterative functions (as of IPF 2.1)' validated and put in  'DocumentationExamplesTest' https://github.com/krasserm/ipf/commit/4f39b87c43b70340e784498354fd158e98599840
- Added examples of generics MessageAdapter types in other tests as well
- Fixed DSLD descriptor to comply with Groovy plugin 2.5.1
