### ISSUE TITLE
Problem with RSP_K21.getRSP_K21_QUERY_RESPONSE();  

### ISSUE THREAD

**Issue by ghost** [krasserm/ipf#69]
There is a problem with the custom HL7 RSP_K21 class org.openehealth.ipf.commons.ihe.pixpdq.definitions.v25.pdq.message.RSP_K21 class in IPF version 2.2.4.

RSP_K21.getRSP_K21_QUERY_RESPONSE() throws always an exception.
To access the RSP_K21_QUERY_RESPONSE  use RSP_K21.get("QUERY_RESPONSE")

This will be fixed in the next versions of IPF. Until then please use the proposed workarround.

**Comment by unixoid** [comment]
Is this already fixed?

**Comment by ghost** [comment]
Will be available in version 2.3-m2 and later

**Comment by unixoid** [comment]
BTW, the same problem exists (did exist) in IPF's RSP_K23 custom class --- I fix it now.
